### ISSUE TITLE
Add Hass.io Addon Support

### ISSUE THREAD

**Issue by qJake** [qJake/HADotNet.CommandCenter#10]
Add support for this addon to be installed via the Hass.io Addon Interface.

Things to consider:

1. Hass.io runs on different architecture - ARMv8 and AMD64 - how is this handled by the Dockerfile that's built or the image(s) that are pulled?
2. For those running Hass.io on an RPi (ARMv8), this runs on Alpine Linux, for which a base Docker image is not available at this time. A Docker image for Alpine ARMv8 will be released with [.NET Core 3.0 in September 2019](https://github.com/dotnet/core/blob/master/roadmap.md), so until that point, a Hass.io addon for RPi images is not possible.

**Comment by nic0dk** [comment]
what about AMD64 hass.io, any timeline on when you will release one? :) btw. 
awesome work!

**Comment by qJake** [comment]
@nic0dk Yep, this would include support for both AMD64 and ARMv8.

**Comment by qJake** [comment]
ARM32v7 support will be added in 0.5.0, releasing this weekend sometime!

AMD64 is still being worked on.

**Comment by qJake** [comment]
Released: https://github.com/qJake/HADotNet.CommandCenter/releases/tag/v0.5.0
