### ISSUE TITLE
No configuration options and errors in logs

### ISSUE THREAD

**Issue by KevSex** [qJake/HADotNet.CommandCenter#105]
## Description

No Settings page to configure and receiving error in logs

## Environment

HACC 0.6.0
Odroid XU4
Ubuntu 18.04.5 LTS armv71

## Steps to Reproduce

Install HACC using the "Easy" method on your site

![image](https://user-images.githubusercontent.com/13280296/90733184-1d398e00-e2c4-11ea-909f-b6758345700a.png)

Looking at other screenshots online, this Settings page should show the long-lived tokens section whereas it's not showing for me.
![image](https://user-images.githubusercontent.com/13280296/90733219-2aef1380-e2c4-11ea-88fc-cf4b8c9047b0.png)

Any help would be appreciated

**Comment by KevSex** [comment]
Using the "beta" option looks to have worked

**Comment by hpapagaj** [comment]
Same problem here. Stable is not as stable as name says. It doesn't work under latest HA. Beta is working.
