### ISSUE TITLE
Configuration doesn't save after restart

### ISSUE THREAD

**Issue by lukewelch** [qJake/HADotNet.CommandCenter#107]
Hi

Im running the Beta Version (1.0.22) and upon a restart non of my pages, layouts, themes or access token are saved. 

Excellent software though :)

**Comment by qJake** [comment]
Can you post your full log text if running from the Supervisor? On the Log tab in the addon config.

Or, if you're just running a straight-up Docker container, you'll need to reproduce the bug while a terminal is attached so you can see and grab the logs.

**Comment by lukewelch** [comment]
info: HADotNet.CommandCenter.Startup[0]
      
        _    _          _____ _____ 
       | |  | |   /\   / ____/ ____|
       | |__| |  /  \ | |   | |     
       |  __  | / /\ \| |   | |     
       | |  | |/ ____ \ |___| |____ 
       |_|  |_/_/    \_\_____\_____|
              
       Home Assistant Command Center
              Version 1.0.22
      
      Now listening on: http://*:8095
      
warn: HADotNet.CommandCenter.Middleware.HAClientInitialization[0]
      Can't initialize HACC API, missing the base URL.
warn: HADotNet.CommandCenter.Middleware.HAClientInitialization[0]
      Can't initialize HACC API, missing the base URL.
info: HADotNet.CommandCenter.Middleware.HAClientInitialization[0]
      HA connection is not initialized, redirecting user to settings area...
warn: HADotNet.CommandCenter.Middleware.HAClientInitialization[0]
      Can't initialize HACC API, missing the access token.
warn: HADotNet.CommandCenter.Middleware.HAClientInitialization[0]
      Can't initialize HACC API, missing the access token.
warn: HADotNet.CommandCenter.Middleware.HAClientInitialization[0]
      Can't initialize HACC API, missing the access token.
warn: HADotNet.CommandCenter.Middleware.HAClientInitialization[0]
      Can't initialize HACC API, missing the access token.
info: HADotNet.CommandCenter.Middleware.HAClientInitialization[0]
      Initializing HACC API with URL http://192.168.0.48:8123 and access token [eyJ0eX•••••••••••Yjt9CA].


On each restart it asks me for an access token.

Also for some reason when I first installed the stable version it installed version 0.6.0 and I cannot uninstall it or update it or install your latest stable. do you know why this may be?

Thanks in advance

**Comment by lukewelch** [comment]
I Found a previous issue on how to remove version 0.6.0

**Comment by lukewelch** [comment]
Hi Jake

just wondering if you managed to replicate the issue? 

thanks

**Comment by qJake** [comment]
Sorry for the delay... can you update to 1.0.25 or newer and let me know if this is still an issue?

Also, please provide full details of your system (how are you running Home Assistant? What version? Are you running HACC via Supervisor or separate Docker container...?)

**Comment by qJake** [comment]
Hi @lukewelch, v1.0.26 or newer should address this - let me know if you're still having any issues. Feel free to reply and reopen the issue.
