### ISSUE TITLE
Timezone not including GMT-1200

### ISSUE THREAD

**Issue by nickrout** [qJake/HADotNet.CommandCenter#11]
I get every number from -1100 to +1200, but not -1200. Running 0.4.1.

Also shouldn't the timezones really be proper text like Pacific/Auckland, rather than just numbers?

**Comment by qJake** [comment]
I'm pulling a list of standard time zones from the system - on Windows, it displays this:

![image](https://user-images.githubusercontent.com/652006/64121795-6e740900-cd65-11e9-92f6-20ba5411fa31.png)

Can you share a screenshot of what it looks like on your system? I may need to just hard-code this list if Linux-based systems don't have a nice list like this. 🙂

**Comment by qJake** [comment]
@nickrout I see what you're saying - on Linux, it doesn't display the names of the timezones, but my list goes from UTC-11 to UTC+14 (weirdly), and maybe I'm not that familiar with timezones, but aren't UTC+12 and UTC-12 equivalent? Can you try UTC+12:00 and let me know if that works and displays the correct time?

Also, some people have had success mapping this volume with Docker: `"/etc/localtime:/etc/localtime:ro"` You can also set the `TZ` environment variable which may work as well.
