### ISSUE TITLE
HACC is unable to reach your Home Assistant instance

### ISSUE THREAD

**Issue by arfrater** [qJake/HADotNet.CommandCenter#115]
## Description

**Error
The settings entered are not valid. HACC is unable to reach your Home Assistant instance. Try your entries again, consult the setup guide for help, or check the logs (console) for more information.**
 is shown after adding the long lived token and setting the Override Asset Base URL

## Environment

Home Assistant 2021.1.5

AMD64 Docker on Linux Debian 

## Steps to Reproduce

Uninstalled 0.6 and installed 1.0.26 went to setup and error occured

## Screenshots

![screenshot](https://user-images.githubusercontent.com/49191109/106285029-b1eee180-628f-11eb-802d-5d92edda9ab0.jpg)

**Comment by arfrater** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/49191109/106285370-2295fe00-6290-11eb-8dfa-479e13c155a4.jpg)

**Comment by qJake** [comment]
That's really strange... it's saying it can't reach that URL, but it's accessible via the internet (I can get to it here).

I'm gonna guess that, for some reason, it's not able to resolve https://<your-HA-install>/api/discovery_info from within the addon, but I don't know why.

One thing you could try is entering `https://<your-HA-install` into the **Override Asset Base URL** field to see if that resolves it.

**Comment by arfrater** [comment]
Well decided to install on another server and connected to HA running ok ??

**Comment by qJake** [comment]
If it connected OK, it doesn't really matter where HACC is installed - it is perfectly OK for it to be on a different server. 😉

Please open a new issue if you run into any other issues, thanks!
