### ISSUE TITLE
person tiles don’t populate

### ISSUE THREAD

**Issue by sr-as2** [qJake/HADotNet.CommandCenter#15]
Hi again!
person tiles don’t populate if we don't have entity_picture set.
Can you fix it ?
thanks !!

**Comment by qJake** [comment]
This will be fixed in 0.5.0, releasing this weekend sometime!

**Comment by qJake** [comment]
Released: https://github.com/qJake/HADotNet.CommandCenter/releases/tag/v0.5.0
