### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by Mdleal** [qJake/HADotNet.CommandCenter#18]
I am having the same issue as described in this [post.]( https://community.home-assistant.io/t/hacc-home-assistant-command-center/134843/80)

**Comment by qJake** [comment]
I'm currently tracking this issue with the layout/grid/drag and drop system that is being used:

* https://github.com/desandro/draggabilly/issues/206
* https://github.com/metafizzy/packery/issues/533

I'm hoping to be able to resolve this once I hear back on one of these.

**Comment by qJake** [comment]
This will be fixed in 0.5.0, releasing this weekend sometime!

**Comment by qJake** [comment]
Released: https://github.com/qJake/HADotNet.CommandCenter/releases/tag/v0.5.0
