### ISSUE TITLE
Tile icon not refreshing

### ISSUE THREAD

**Issue by MarekLe** [qJake/HADotNet.CommandCenter#21]
I have a light tile. The light is an entity of sonoff with ESPHome connected to HA.
Touching tile working fine - icon changing from on to off etc. and light turns On/Off.
But - when I switch the light witch a button on  sonoff - icon on HACC tile not changing from On to Off.

**Comment by qJake** [comment]
Looks like I'll need to add support for auto-refreshing this entity type, I must have missed that for this tile. Thanks for reporting this!

**Comment by qJake** [comment]
This will be fixed in 0.5.0, releasing this weekend sometime!

**Comment by qJake** [comment]
Released: https://github.com/qJake/HADotNet.CommandCenter/releases/tag/v0.5.0
