### ISSUE TITLE
Add custom state name

### ISSUE THREAD

**Issue by MarekLe** [qJake/HADotNet.CommandCenter#29]
## Description

I have a state tile for inform me than it's day to do something. It's now presenting 'On/Off' state on the dashboard. Is it possible to add custom names in ptile properties?
Another big feature would be possibility to set a color for state. For example red for On ane black for Off.

## Environment

0.5.1
RPi 3.

## Steps to Reproduce

1. List out the
2. Steps to take to
3. Reproduce the issue

**Comment by qJake** [comment]
@MarekLe What is the entity ID (or, at least the type - the first part before the dot - like a `input_binary` or a `switch` or...?) Also, can you tell me the attributes on that entity in Developer Tools > States? The primary state of the entity is probably "On/Off" but if there are other properties on the entity that we can use, that may be an easier route to go.

**Comment by qJake** [comment]
Thanks @MarekLe! I will make a point to add custom state names (changing "on"/"off") in a future release.

FYI, I am also planning to support calendar integration directly so you can print your agenda out on a tile! 😄

**Comment by qJake** [comment]
Done, and will be released in v1.0! Here's what the options look like:

![image](https://user-images.githubusercontent.com/652006/73718281-abac4080-46e1-11ea-8bbd-560835920206.png)
