### ISSUE TITLE
Feature request: Allow groups for Person Tiles

### ISSUE THREAD

**Issue by mf-social** [qJake/HADotNet.CommandCenter#30]
Currently the Person Tile allows individual trackers, or Persons - The Person component is unreliable for me so I use a Group of device trackers to establish presence.  Would be nice to be able to select the group to display presence on one of these tiles.

Thanks.

**Comment by qJake** [comment]
@mf-social From a set of `device_tracker` or `person` entities, how would the dashboard know which one's information to display on the dashboard? We need the entity's state (its location/zone), and an `entity_picture` to display, so how would it know which one to select from a group?

**Comment by mf-social** [comment]
Entity picture isn't drawn from the entity for other cards, one has to specify an mdi - could allow to add entity picture in the same way possibly?  Or just draw it from the group entity? (wouold actually be nice if other tiles did this if you didn't specify an mdi)

As for the state (location/zone) of the entity, I use the sate of the group to determine presence, that's kind of the point.

**Comment by qJake** [comment]
@mf-social I feel like, based on this description, the State tile gets you pretty close to what you want. If you plug your "person group" into a State tile, what is missing as an option that you would want? Just the ability to set a profile picture and/or an MDI icon, instead of just displaying the state by itself as a label?

**Comment by mf-social** [comment]
I didn't really think about the state tile if I'm honest, I just wanted to represent a 'person' (ie a human rather than an entity from the person component) and thought the person tile was the place to go 🙂
