### ISSUE TITLE
No camera image - Hass.io addon Oracle VM 64Bit

### ISSUE THREAD

**Issue by frank451a** [qJake/HADotNet.CommandCenter#31]
unable to view cameras on dashboard tried generic, onvif hikvision and axis camera types.

Running on Oracle VM - 64 Bit 
Hass.io .098.4 Hassos 2.12
HACC .0.5.1
![image](https://user-images.githubusercontent.com/26573878/64539890-33e70f00-d317-11e9-84e0-390d81da25c5.png)

**Comment by FrGrump** [comment]
having the same issue with Ring doorbell and Floodlight Cam.

**Comment by echopage** [comment]
same issue with xiaofang, on raspberry pi 3b, hassio 98.5 hassos 2.12

**Comment by qJake** [comment]
Fixed and released in v0.5.2!
