### ISSUE TITLE
Switches not refresh

### ISSUE THREAD

**Issue by DieguitoCigala** [qJake/HADotNet.CommandCenter#33]
## Description

When I turn on or turn off a switch outside of dashboard, the switch of dashboard not refresh to the current state.

## Environment

HACC version 0.5.1
Hass.io on a NUC Inter iCore i5 with docker
Homeassistant version 0.98.5
I use Safari on iPhone XS with iOS 12.4 and on iPad with iOS 12.4.1 (also I've tried Chrome)

## Steps to Reproduce

1. Open dashboard on iPad or iPhone
2. I turn on or turn off some switch
3. Wait to refresh the dasboard
4. The dashboard not refresh

## Screenshots

<Paste or upload screenshots here.>

**Comment by qJake** [comment]
Fixed and released in v0.5.2!

**Comment by DieguitoCigala** [comment]
With this update the switches refresh when your turn on but not when you turn off. I don’t know why.

**Comment by qJake** [comment]
@DieguitoCigala When you use the standard Home Assistant UI to toggle the switch, does it take a moment for the system to recognize that the switch was flipped, or is it pretty instantaneous?

HACC just waits 1,000ms (I think) and then re-requests the state of the switch. So if your switch takes longer than 1,000ms to turn off, that may be the problem. Or, if it's a dimmer, that can also cause it.

I may need to adjust this, or allow the user to enter their own delay.

**Comment by DieguitoCigala** [comment]
It's pretty instantaneous but I don't think that it's as instant as 1 mS. I think that it's a little more.

It's not a dimmer.
