### ISSUE TITLE
Export config error

### ISSUE THREAD

**Issue by wellsy57** [qJake/HADotNet.CommandCenter#34]
## Description
Export config error

<Describe the problem.>

I have a problem with Exporting my config where I get an error which reads:

`hacc-export-20190912-071505.config.jsonFailed - Network error`

## Environment

<What version of HACC are you running?>

0.5.1.0, built on 09/08/2019 15:30:28

<What environment is it? Hass.io on a Raspberry Pi 3B+? AMD64 Docker on Alpine 3.10?>

Installed on QNAP using ContainerStation (Docker)

## Steps to Reproduce

1. HA Command Center – Admin Area
2. Click Export
3. error appears (see lower left screenshot below....download error)

## Screenshots

<img width="898" alt="HACC ErrorCrop" src="https://user-images.githubusercontent.com/39934693/64771455-559ffa80-d592-11e9-9580-3fd5ef1fd31c.png">

<Paste or upload screenshots here.>

**Comment by qJake** [comment]
@wellsy57 I am running the exact same setup as you (RPi 3B+ / Hass.io) and I can export my config - the only difference is that I am running 0.5.2 not 0.5.1. I don't think I made any improvements for this between those two versions but you may try updating to see if that resolves the issue.

It also looks like it downloaded the file in your screenshot - is it successfully downloading the config file and just also throwing the error, or is the config file not downloading at all?

Does this happen some of the time, or always?

**Comment by wellsy57** [comment]
@qJake Thanks for getting back to me! There is a difference in our installations though....mine is "Installed on QNAP using ContainerStation (Docker)".
The download fails...nothing downloads. 
I would like to move to 0,5,2 but was waiting to try to get my config so I dont have to setup from scratch again but I may just try to find the config in my docker...I'll let you know if that is successful.
Cheers for all your work on this...its a very good dashboard setup!

**Comment by qJake** [comment]
@wellsy57 Other people running a direct Docker container have been able to persist their `config.json` file by including a parameter when you run it: `-v /your/outside/path/to/config.json:/app/config.json` That may allow you to retrieve a copy of the `config.json` file so that you can persist it and upgrade!

**Comment by qJake** [comment]
@wellsy57 I changed something in v0.6.0 for this, can you update and tell me if you're still having the problem?
