### ISSUE TITLE
Override Label for Light Tile

### ISSUE THREAD

**Issue by wellsy57** [qJake/HADotNet.CommandCenter#35]
## Describe the new functionality

Add an Override Label for Light Tile Entity

## What will it look like in the Admin area?

It would be the same as the existing functionality in the Switch Tile Admin Area

## What will it look like on the dashboard?

The dashboard will then have the override lable text displayed.

## How will it work for standalone users vs. Hass.io Addon users?

Same for all users.

**Comment by qJake** [comment]
Released in [v0.6.0](https://github.com/qJake/HADotNet.CommandCenter/releases/tag/v0.6.0), closing this issue.
