### ISSUE TITLE
Input boolean

### ISSUE THREAD

**Issue by Keplernl** [qJake/HADotNet.CommandCenter#40]
## Describe the new functionality
Input boolean works the same as a switch, but slightly different function
## What will it look like in the Admin area?
Same as switch

## What will it look like on the dashboard?
Like a switch that can be turned on and off

## How will it work for standalone users vs. Hass.io Addon users?
?

**Comment by qJake** [comment]
Already done! See: https://github.com/qJake/HADotNet.CommandCenter/issues/39
