### ISSUE TITLE
Cant uninstall HACC

### ISSUE THREAD

**Issue by Mariusthvdb** [qJake/HADotNet.CommandCenter#42]
## Description

<Describe the problem.>
It isnt possible to uninstall HACC

## Environment

<What version of HACC are you running?>

<What environment is it? Hass.io on a Raspberry Pi 3B+? AMD64 Docker on Alpine 3.10?>
Hassio on RPI4

## Steps to Reproduce

1. List out the
2. Steps to take to
3. Reproduce the issue

please see
https://community.home-assistant.io/t/hacc-home-assistant-command-center/134843/184?u=mariusthvdb
```
19-09-18 08:00:09 INFO (SyncWorker_2) [hassio.docker.interface] Remove image qjake/hacc-hassio-armv7 with latest and 
19-09-18 08:00:09 WARNING (SyncWorker_2) [hassio.docker.interface] Can't remove image qjake/hacc-hassio-armv7: 400 Client Error: Bad Request ("invalid reference format")

```## Screenshots

<Paste or upload screenshots here.>

**Comment by qJake** [comment]
This is a known issue, waiting on this thread for a fix: https://github.com/home-assistant/hassio/issues/1280

**Comment by qJake** [comment]
Keeping open.

**Comment by Mariusthvdb** [comment]
why was this closed??
bug is still alive and kicking on 101.2, as I have also reported on https://github.com/home-assistant/hassio/issues/1280

**Comment by qJake** [comment]
@Mariusthvdb The stale bot is a bit aggressive. I'll check the settings.

If you add a comment on a stale issue, it will "refresh" it, so to speak.

**Comment by Mariusthvdb** [comment]
this is still an issue, so please keep open

**Comment by qJake** [comment]
Keep open.

**Comment by qJake** [comment]
As of Feb 7, I identified and fixed this issue. It will be released with v1.0 (or, tentatively being called "v1.1" now since there has been a lot of beta testing with "v1.0" already).

Closing as fixed!

**Comment by nelbs** [comment]
Unfortunately I ran into the same problem. After I installed the addon HACC 0.6 I noticed that I could beter install the beta 1.019.

Uninstalling the addon results in an error. I tried to delete the container in portainer, update Home assistant and reboot the host as @Mariusthvdb mentioned in https://github.com/home-assistant/supervisor/issues/1280#issuecomment-558605230 suggested.

Unfortunately that didn't help.  Is there a way how i can remove the addon?

**Comment by qJake** [comment]
@nelbs You'll have to wait for a newer version (e.g. 1.0) to come out. The issue was in the addon configuration, and that is only fixed in the newer images that we have not released officially yet.

I want to say that someone else found a workaround for how to remove it but I'm not sure where or how exactly.
