### ISSUE TITLE
Endless background task

### ISSUE THREAD

**Issue by sylas** [qJake/HADotNet.CommandCenter#52]
## Description

Every few days the "Community" page cannot finish the background task (the orange line is moving over and over). After restarting HA problem is solved for a few days. 
The JS concole does not show anything suspect.

## Environment

Integration version: | 0.20.8
Frontend version: | 20200104192235

Hass.io on a Raspberry Pi 3B+

## Steps to Reproduce

1. Open the Community page.
2. Observe the orange strip moving over and over and the alert message, as in the attached screnshot. Only the HA restart helps. However, after few days problem will appear again.

## Screenshots

![obraz](https://user-images.githubusercontent.com/1716833/72819273-3fefbf80-3c6d-11ea-9825-af58678a8848.png)

**Comment by qJake** [comment]
@sylas You have the wrong project - HACC is a tablet interface for Home Assistant. You want HACS, the community store.

Here is the forum thread for HACS:

https://community.home-assistant.io/t/custom-component-hacs/121727
