### ISSUE TITLE
Install Wiki needs update

### ISSUE THREAD

**Issue by SiliconAvatar** [qJake/HADotNet.CommandCenter#68]
## Description

On wiki for this project, in the "Installing via Hass.io Addons" section, it states (in step 1) to navigate to the Hass.io tab. This language should be updated to state "Navigate to the Supervisor tab" since it was recently renamed. 

I do not see a way to edit or make a PR on the wiki itself, hence this issue report.

## Environment

N/A

## Steps to Reproduce

N/A

## Screenshots

N/A

**Comment by qJake** [comment]
Thanks for catching this, fixed! 🙂
