### ISSUE TITLE
Weather details

### ISSUE THREAD

**Issue by themsk666** [qJake/HADotNet.CommandCenter#77]
why on my HA command center for the weather sensor it's only show partlycloudy, no temperature value no anything else. in title edit there is the weather.home sensor selected. in the home assistant this sensor show all info.

**Comment by qJake** [comment]
Hi there @themsk666, the Weather tile does not yet support the `weather` entity type in Home Assistant.

You'll need to provide sensors that provide each respective value. Currently, the Dark Sky API platform is best supported, but you can play with other platforms to see if you can get it to work as well.

For example - my setup:

![image](https://user-images.githubusercontent.com/652006/77833270-10947d80-710a-11ea-8e4d-a611e340f14c.png)
