### ISSUE TITLE
Cover icons are not updating with state changes

### ISSUE THREAD

**Issue by avishayil** [qJake/HADotNet.CommandCenter#88]
When opening cover, for example, it's state is changing to "open" where the icon is designed to support "on" state.

<Describe the problem.>

## Environment

1.0.16
Raspberry PI 3B

<What environment is it? Hass.io on a Raspberry Pi 3B+? AMD64 Docker on Alpine 3.10?>

- Add switch tile cover style
- Attach icons for "on" and "off" displays
- Open cover
- Icons are always staying "off"

## Screenshots

![screenshot](https://i.imgur.com/iFwRx2r.png)

**Comment by qJake** [comment]
Ah, interesting. I think this is an issue with it being "open"/"closed" vs. "on"/"off". I will investigate. Should be fixed before the next major release.

**Comment by qJake** [comment]
I think I've addressed this in 1.0.17 and higher (will be built and released within 20 minutes from this post), please let me know if this is still not fixed and I can reopen.
