### ISSUE TITLE
UI doesn't work on old android tablet.

### ISSUE THREAD

**Issue by nordikafiles** [qJake/HADotNet.CommandCenter#99]
## Description
Probably it is because of using of some quite modern javascript features (like classes, async/await etc).

## Possible solution
I guess it could be solved by transpiling es6 to es5 (for example using babel).

**Comment by qJake** [comment]
Yes, we [transpile to ES6](https://github.com/qJake/HADotNet.CommandCenter/blob/master/HADotNet.CommandCenter/tsconfig.json), so I'm not sure how we would go about making this ES5-compatible while not harming any devices that are ES6-capable, do you have any ideas?

**Comment by qJake** [comment]
The latest beta of HACC has a "Debug" tile that you can add, that when you click on it, will pop up browser information onto the tablet/device.

Try this, and provide a picture/screenshot of your device. I suspect that it is unfortunately too old/slow to support the features that HACC requires, but with this debug tile, you can at least get confirmation.
